# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

america = Team.create(name: "United States of America", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/250px-Flag_of_the_United_States.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Reed Smith", position: "Chaser", team: america)
Player.create(name: "Lorenzo Johnson", position: "Chaser", team: america)
Player.create(name: "Jerome Jones", position: "Chaser", team: america)
Player.create(name: "Isabella Miller", position: "Beater", team: america)
Player.create(name: "Sophia Moore", position: "Beater", team: america)
Player.create(name: "Elijah Brown", position: "Seeker", team: america)
Player.create(name: "Ethan Taylor", position: "Keeper", team: america)
canada = Team.create(name: "Canada", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/250px-Flag_of_Canada_%28Pantone%29.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Shannon Tremblay", position: "Chaser", team: canada)
Player.create(name: "Liam Roy", position: "Chaser", team: canada)
Player.create(name: "Lindsay Leblanc", position: "Chaser", team: canada)
Player.create(name: "Amelia Gagne", position: "Beater", team: canada)
Player.create(name: "Jean Bouchard", position: "Beater", team: canada)
Player.create(name: "Logan Macdonald", position: "Seeker", team: canada)
Player.create(name: "Sidney Desjardins", position: "Keeper", team: canada)
mexico = Team.create(name: "Mexico", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/250px-Flag_of_Mexico.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Ximena Hernández", position: "Chaser", team: mexico)
Player.create(name: "Sofía Lòpez", position: "Chaser", team: mexico)
Player.create(name: "Alejandro Flores", position: "Chaser", team: mexico)
Player.create(name: "Juan Carlos Gómez", position: "Beater", team: mexico)
Player.create(name: "Miguel Ángel Sánchez", position: "Beater", team: mexico)
Player.create(name: "Camila González", position: "Seeker", team: mexico)
Player.create(name: "Angel Martìnez", position: "Keeper", team: mexico)
brazil = Team.create(name: "Brazil", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/250px-Flag_of_Brazil.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Monica Silva", position: "Chaser", team: brazil)
Player.create(name: "Felicita Santos", position: "Chaser", team: brazil)
Player.create(name: "Antônio Sousa", position: "Chaser", team: brazil)
Player.create(name: "Victoriano Oliveira", position: "Beater", team: brazil)
Player.create(name: "Tito Pereira", position: "Beater", team: brazil)
Player.create(name: "Fernando Lima", position: "Seeker", team: brazil)
Player.create(name: "Bruno Ferreira", position: "Keeper", team: brazil)
colombia = Team.create(name: "Colombia", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/250px-Flag_of_Colombia.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Diego Jiménez", position: "Chaser", team: colombia)
Player.create(name: "Angie Moreno", position: "Chaser", team: colombia)
Player.create(name: "Daniela Díaz", position: "Chaser", team: colombia)
Player.create(name: "Juan Diego Ramírez", position: "Beater", team: colombia)
Player.create(name: "Andres Rodríguez", position: "Beater", team: colombia)
Player.create(name: "María Alejandra Gómez", position: "Seeker", team: colombia)
Player.create(name: "Gabriela García", position: "Keeper", team: colombia)
argentina = Team.create(name: "Argentina", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/250px-Flag_of_Argentina.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Martin Fernández", position: "Chaser", team: argentina)
Player.create(name: "Ines Álvarez", position: "Chaser", team: argentina)
Player.create(name: "Matias Vásquez", position: "Chaser", team: argentina)
Player.create(name: "Catalina Blanco", position: "Beater", team: argentina)
Player.create(name: "Ignacio Ruiz", position: "Beater", team: argentina)
Player.create(name: "Juan Manuel Alonso", position: "Seeker", team: argentina)
Player.create(name: "Martina Torres", position: "Keeper", team: argentina)
venezuela = Team.create(name: "Venezuela", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Flag_of_Venezuela_%28state%29.svg/250px-Flag_of_Venezuela_%28state%29.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "José Mata", position: "Chaser", team: venezuela)
Player.create(name: "Carmen Valencia", position: "Chaser", team: venezuela)
Player.create(name: "Genesis Rivas", position: "Chaser", team: venezuela)
Player.create(name: "Henry José Abreu", position: "Beater", team: venezuela)
Player.create(name: "Ruben Arias", position: "Beater", team: venezuela)
Player.create(name: "Andrea Rojas", position: "Seeker", team: venezuela)
Player.create(name: "Alberto Fayola", position: "Keeper", team: venezuela)
australia = Team.create(name: "Australia", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/250px-Flag_of_Australia_%28converted%29.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Thomas Campbell", position: "Chaser", team: australia)
Player.create(name: "Mason White", position: "Chaser", team: australia)
Player.create(name: "Lucas Lee", position: "Chaser", team: australia)
Player.create(name: "Mackenzie Johnson", position: "Beater", team: australia)
Player.create(name: "Ellie Taylor", position: "Beater", team: australia)
Player.create(name: "Teagan Anderson", position: "Seeker", team: australia)
Player.create(name: "Zoe Thompson", position: "Keeper", team: australia)

ireland = Team.create(name: "Ireland", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/250px-Flag_of_Ireland.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Fiona Murphy", position: "Chaser", team: ireland)
Player.create(name: "Shannon Kelly", position: "Chaser", team: ireland)
Player.create(name: "Elena O'Sullivan", position: "Chaser", team: ireland)
Player.create(name: "Connor Walsh", position: "Beater", team: ireland)
Player.create(name: "Sean O'Brien", position: "Beater", team: ireland)
Player.create(name: "Molly Byrne", position: "Seeker", team: ireland)
Player.create(name: "Keegan Ryan", position: "Keeper", team: ireland)
bulgaria = Team.create(name: "Bulgaria", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/250px-Flag_of_Bulgaria.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Miroslav Arsov", position: "Chaser", team: bulgaria)
Player.create(name: "Viktor Kalchev", position: "Chaser", team: bulgaria)
Player.create(name: "Nikol Rangelov", position: "Chaser", team: bulgaria)
Player.create(name: "Georgi Sokoloff", position: "Beater", team: bulgaria)
Player.create(name: "Aleksandra Lukov", position: "Beater", team: bulgaria)
Player.create(name: "Nikolay Tanev", position: "Seeker", team: bulgaria)
Player.create(name: "Monika Dimitrov", position: "Keeper", team: bulgaria)
russia = Team.create(name: "Russia", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/250px-Flag_of_Russia.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Ivan Filatov", position: "Chaser", team: russia)
Player.create(name: "Oksana Uglov", position: "Chaser", team: russia)
Player.create(name: "Tatyana Tsaryov", position: "Chaser", team: russia)
Player.create(name: "Sergei Cherkasov", position: "Beater", team: russia)
Player.create(name: "Evgeni Shchukin", position: "Beater", team: russia)
Player.create(name: "Tasha Kholodov", position: "Seeker", team: russia)
Player.create(name: "Igor Khabalov", position: "Keeper", team: russia)
germany = Team.create(name: "Germany", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/250px-Flag_of_Germany.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Tobias Schneider", position: "Chaser", team: germany)
Player.create(name: "Florian Fischer", position: "Chaser", team: germany)
Player.create(name: "Ella Weber", position: "Chaser", team: germany)
Player.create(name: "Wolfgang Hoffmann", position: "Beater", team: germany)
Player.create(name: "Mats Meyer", position: "Beater", team: germany)
Player.create(name: "Verena Zimmermann", position: "Seeker", team: germany)
Player.create(name: "Heidi Schulz", position: "Keeper", team: germany)
england = Team.create(name: "England", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/250px-Flag_of_England.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "George Davies", position: "Chaser", team: england)
Player.create(name: "Marie Evans", position: "Chaser", team: england)
Player.create(name: "Hope Taylor", position: "Chaser", team: england)
Player.create(name: "Robert Thompson", position: "Beater", team: england)
Player.create(name: "Demi Smith", position: "Beater", team: england)
Player.create(name: "Harry Wright", position: "Seeker", team: england)
Player.create(name: "Red Jones", position: "Keeper", team: england)
france = Team.create(name: "France", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/250px-Flag_of_France.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Pauline Bernard", position: "Chaser", team: france)
Player.create(name: "Beau Couture", position: "Chaser", team: france)
Player.create(name: "Wendie Laurent", position: "Chaser", team: france)
Player.create(name: "Grace Robert", position: "Beater", team: france)
Player.create(name: "Stephen Durand", position: "Beater", team: france)
Player.create(name: "Thibault Dubois", position: "Seeker", team: france)
Player.create(name: "Trevor Moreau", position: "Keeper", team: france)
spain = Team.create(name: "Spain", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/250px-Flag_of_Spain.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Ricard Martínez", position: "Chaser", team: spain)
Player.create(name: "Javier Muñoz", position: "Chaser", team: spain)
Player.create(name: "Rodolfo García", position: "Chaser", team: spain)
Player.create(name: "Leila Sánchez", position: "Beater", team: spain)
Player.create(name: "Alexia Sánchez", position: "Beater", team: spain)
Player.create(name: "Angela López", position: "Seeker", team: spain)
Player.create(name: "Marta Díaz", position: "Keeper", team: spain)
ukraine = Team.create(name: "Ukraine", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/250px-Flag_of_Ukraine.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Anastasia Davydenko", position: "Chaser", team: ukraine)
Player.create(name: "Dmytro Zherdev", position: "Chaser", team: ukraine)
Player.create(name: "Lyudmyla Vann", position: "Chaser", team: ukraine)
Player.create(name: "Oleksandr Burgos", position: "Beater", team: ukraine)
Player.create(name: "Volodymyr Vovk", position: "Beater", team: ukraine)
Player.create(name: "Andrii Pavlovych", position: "Seeker", team: ukraine)
Player.create(name: "Iryna Zelenko", position: "Keeper", team: ukraine)

indonesia = Team.create(name: "Indonesia", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/250px-Flag_of_Indonesia.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Ahmad Juliani", position: "Chaser", team: indonesia)
Player.create(name: "Kadek Islami", position: "Chaser", team: indonesia)
Player.create(name: "Gesang Riski", position: "Chaser", team: indonesia)
Player.create(name: "Jayachandra Wijaya", position: "Beater", team: indonesia)
Player.create(name: "Harum Saputra", position: "Beater", team: indonesia)
Player.create(name: "Octavianti Huda", position: "Seeker", team: indonesia)
Player.create(name: "Ramzil Zulfi", position: "Keeper", team: indonesia)
india = Team.create(name: "India", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/250px-Flag_of_India.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Deepti Patel", position: "Chaser", team: india)
Player.create(name: "Anuja Acharya", position: "Chaser", team: india)
Player.create(name: "Ekta Babu", position: "Chaser", team: india)
Player.create(name: "Dipsan Bakshi", position: "Beater", team: india)
Player.create(name: "Amit Chabra", position: "Beater", team: india)
Player.create(name: "Kawal Varma", position: "Seeker", team: india)
Player.create(name: "Hardik Dhar", position: "Keeper", team: india)
china = Team.create(name: "China", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/250px-Flag_of_the_People%27s_Republic_of_China.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Tian Wang", position: "Chaser", team: china)
Player.create(name: "Wu Li", position: "Chaser", team: china)
Player.create(name: "Du Zhang", position: "Chaser", team: china)
Player.create(name: "Ao Liu", position: "Beater", team: china)
Player.create(name: "Meng Yang", position: "Beater", team: china)
Player.create(name: "Guo Chen", position: "Seeker", team: china)
Player.create(name: "Han Zhao", position: "Keeper", team: china)
bangladesh = Team.create(name: "Bangladesh", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/250px-Flag_of_Bangladesh.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Fazla Azim", position: "Chaser", team: bangladesh)
Player.create(name: "Rashel Chakma", position: "Chaser", team: bangladesh)
Player.create(name: "Masura Sarkar", position: "Chaser", team: bangladesh)
Player.create(name: "Marzia Islam", position: "Beater", team: bangladesh)
Player.create(name: "Sanjida Hossain", position: "Beater", team: bangladesh)
Player.create(name: "Arshad Hasan", position: "Seeker", team: bangladesh)
Player.create(name: "Sabina Rabby", position: "Keeper", team: bangladesh)
philippines = Team.create(name: "Philippines", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/250px-Flag_of_the_Philippines.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Katrina Santos", position: "Chaser", team: philippines)
Player.create(name: "Myla Mendoza", position: "Chaser", team: philippines)
Player.create(name: "Peter Cruz", position: "Chaser", team: philippines)
Player.create(name: "Jessie Garcia", position: "Beater", team: philippines)
Player.create(name: "Kim Reyes", position: "Beater", team: philippines)
Player.create(name: "Thelma Bautista", position: "Seeker", team: philippines)
Player.create(name: "Rikko Torres", position: "Keeper", team: philippines)
japan = Team.create(name: "Japan", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Japan%28bordered%29.svg/250px-Flag_of_Japan%28bordered%29.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Ayaka Sato", position: "Chaser", team: japan)
Player.create(name: "Shiori Suzuki", position: "Chaser", team: japan)
Player.create(name: "Asato Takahashi", position: "Chaser", team: japan)
Player.create(name: "Mayo Watanabe", position: "Beater", team: japan)
Player.create(name: "Takashi Ito", position: "Beater", team: japan)
Player.create(name: "Kentaro Nakamura", position: "Seeker", team: japan)
Player.create(name: "Masahiro Yamamoto", position: "Keeper", team: japan)
korea = Team.create(name: "South Korea", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/250px-Flag_of_South_Korea.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Young-ju Kim", position: "Chaser", team: korea)
Player.create(name: "Min-a Yi", position: "Chaser", team: korea)
Player.create(name: "Min-ji Pak", position: "Chaser", team: korea)
Player.create(name: "Jae-wook Jung", position: "Beater", team: korea)
Player.create(name: "Yong-chan Kang", position: "Beater", team: korea)
Player.create(name: "Hye-ri Shin", position: "Seeker", team: korea)
Player.create(name: "Hong-suk Cho", position: "Keeper", team: korea)
thailand = Team.create(name: "Thailand", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/250px-Flag_of_Thailand.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Aat Sirichai", position: "Chaser", team: thailand)
Player.create(name: "Ananada Kovit", position: "Chaser", team: thailand)
Player.create(name: "Aom Kohsoom", position: "Chaser", team: thailand)
Player.create(name: "Aroon Srisuk", position: "Beater", team: thailand)
Player.create(name: "Karnchana Kannika", position: "Beater", team: thailand)
Player.create(name: "Natcha Suriyawong", position: "Seeker", team: thailand)
Player.create(name: "Boonsri Busarakham", position: "Keeper", team: thailand)

turkey = Team.create(name: "Turkey", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/250px-Flag_of_Turkey.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Beyza Yilmaz", position: "Chaser", team: turkey)
Player.create(name: "Seyma Tata", position: "Chaser", team: turkey)
Player.create(name: "Aylin Tabak", position: "Chaser", team: turkey)
Player.create(name: "Emre Mogul", position: "Beater", team: turkey)
Player.create(name: "Kadir Kocak", position: "Beater", team: turkey)
Player.create(name: "Gokhan Dogan", position: "Seeker", team: turkey)
Player.create(name: "Zehra Barak", position: "Keeper", team: turkey)
pakistan = Team.create(name: "Pakistan", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/250px-Flag_of_Pakistan.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Sadia Farooqi", position: "Chaser", team: pakistan)
Player.create(name: "Muhammed Tirmzi", position: "Chaser", team: pakistan)
Player.create(name: "Rashid Sadat", position: "Chaser", team: pakistan)
Player.create(name: "Arslan Naqvi", position: "Beater", team: pakistan)
Player.create(name: "Bismah Rizvi", position: "Beater", team: pakistan)
Player.create(name: "Ayesha Zaidi", position: "Seeker", team: pakistan)
Player.create(name: "Abu Jafari", position: "Keeper", team: pakistan)
nigeria = Team.create(name: "Nigeria", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/250px-Flag_of_Nigeria.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Samuel Mohammed", position: "Chaser", team: nigeria)
Player.create(name: "Glory Adebayo", position: "Chaser", team: nigeria)
Player.create(name: "Peace Oni", position: "Chaser", team: nigeria)
Player.create(name: "Francis Eze", position: "Beater", team: nigeria)
Player.create(name: "Moses Adeyemi", position: "Beater", team: nigeria)
Player.create(name: "Joy Okafor", position: "Seeker", team: nigeria)
Player.create(name: "Emmanuel Pepple", position: "Keeper", team: nigeria)
egypt = Team.create(name: "Egypt", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/250px-Flag_of_Egypt.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Rashad Ahmed", position: "Chaser", team: egypt)
Player.create(name: "Mariam Hassan", position: "Chaser", team: egypt)
Player.create(name: "Salma Ali", position: "Chaser", team: egypt)
Player.create(name: "Sherif Ibrahim", position: "Beater", team: egypt)
Player.create(name: "Abdallah Mostafa", position: "Beater", team: egypt)
Player.create(name: "Nubia Mohamed", position: "Seeker", team: egypt)
Player.create(name: "Omar Salah", position: "Keeper", team: egypt)
ethiopia = Team.create(name: "Ethiopia", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/250px-Flag_of_Ethiopia.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Eden Nuru", position: "Chaser", team: ethiopia)
Player.create(name: "Omod Kebret", position: "Chaser", team: ethiopia)
Player.create(name: "Zulka Kidanu", position: "Chaser", team: ethiopia)
Player.create(name: "Gosaye Tulu", position: "Beater", team: ethiopia)
Player.create(name: "Kidest Vassalo", position: "Beater", team: ethiopia)
Player.create(name: "Nebil Bekele", position: "Seeker", team: ethiopia)
Player.create(name: "Abel Wolde", position: "Keeper", team: ethiopia)
congo = Team.create(name: "Democratic Republic of the Congo", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/250px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Japhie Mutombo", position: "Chaser", team: congo)
Player.create(name: "Kris Bemba", position: "Chaser", team: congo)
Player.create(name: "Alexandrine Muamba", position: "Chaser", team: congo)
Player.create(name: "Emmanuel Lumumba", position: "Beater", team: congo)
Player.create(name: "Damien Zakuani", position: "Beater", team: congo)
Player.create(name: "Lylie Mudiay", position: "Seeker", team: congo)
Player.create(name: "Yannick Botende", position: "Keeper", team: congo)
southafrica = Team.create(name: "South Africa", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/250px-Flag_of_South_Africa.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Karabo Ntuli", position: "Chaser", team: southafrica)
Player.create(name: "Thato Jones", position: "Chaser", team: southafrica)
Player.create(name: "Bokamoso Tyron", position: "Chaser", team: southafrica)
Player.create(name: "Kamogelo Jafta", position: "Beater", team: southafrica)
Player.create(name: "Kungawo Ismail", position: "Beater", team: southafrica)
Player.create(name: "Iminathi Letsoalo", position: "Seeker", team: southafrica)
Player.create(name: "Bandile Kapp", position: "Keeper", team: southafrica)
tanzania = Team.create(name: "Tanzania", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/250px-Flag_of_Tanzania.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
Player.create(name: "Abdul Mohamedi", position: "Chaser", team: tanzania)
Player.create(name: "Imani Omary", position: "Chaser", team: tanzania)
Player.create(name: "Irene Kibasu", position: "Chaser", team: tanzania)
Player.create(name: "Leyla Muruga", position: "Beater", team: tanzania)
Player.create(name: "Joseph Saleh", position: "Beater", team: tanzania)
Player.create(name: "Aailiyah Pascal", position: "Seeker", team: tanzania)
Player.create(name: "Jamil Yunzu", position: "Keeper", team: tanzania)

Week.create(name: "Week 1", games_completed: false, date: "03 30 2030")
Week.create(name: "Week 2", games_completed: false, date: "04 06 2030")
Week.create(name: "Week 3", games_completed: false, date: "04 13 2030")
Week.create(name: "Week 4", games_completed: false, date: "04 20 2030")
Week.create(name: "Week 5", games_completed: false, date: "04 27 2030")
Week.create(name: "Week 6", games_completed: false, date: "05 04 2030")
Week.create(name: "Week 7", games_completed: false, date: "05 11 2030")
Week.create(name: "Week 8", games_completed: false, date: "05 18 2030")
Week.create(name: "Week 9", games_completed: false, date: "05 25 2030")
Week.create(name: "Week 10", games_completed: false, date: "06 01 2030")
Week.create(name: "Week 11", games_completed: false, date: "06 08 2030")
Week.create(name: "Week 12", games_completed: false, date: "06 15 2030")
Week.create(name: "Week 13", games_completed: false, date: "06 22 2030")
Week.create(name: "Week 14", games_completed: false, date: "06 29 2030")
PlayoffWeek.create(name: "Week 15: Round 1", games_completed: false, date: "07 06 2030")
PlayoffWeek.create(name: "Week 16: Quarter Finals", games_completed: false, date: "07 13 2030")
PlayoffWeek.create(name: "Week 17: Semi Finals", games_completed: false, date: "07 20 2030")
PlayoffWeek.create(name: "Week 18: Finals", games_completed: false, date: "08 03 2030")

# Division: Europe Games
Game.create(week_id: Week.all[0].id, home_id: 9, away_id: 10, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 9, away_id: 11, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 9, away_id: 12, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 9, away_id: 13, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 9, away_id: 14, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 9, away_id: 15, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 9, away_id: 16, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 10, away_id: 11, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 10, away_id: 12, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 10, away_id: 13, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 10, away_id: 14, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 10, away_id: 15, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 10, away_id: 16, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 10, away_id: 9, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[0].id, home_id: 11, away_id: 12, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 11, away_id: 13, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 11, away_id: 14, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 11, away_id: 15, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 11, away_id: 16, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 11, away_id: 9, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 11, away_id: 10, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 12, away_id: 13, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 12, away_id: 14, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 12, away_id: 15, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 12, away_id: 16, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 12, away_id: 9, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 12, away_id: 10, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 12, away_id: 11, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[0].id, home_id: 13, away_id: 14, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 13, away_id: 15, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 13, away_id: 16, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 13, away_id: 9, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 13, away_id: 10, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 13, away_id: 11, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 13, away_id: 12, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 14, away_id: 15, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 14, away_id: 16, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 14, away_id: 9, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 14, away_id: 10, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 14, away_id: 11, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 14, away_id: 12, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 14, away_id: 13, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[0].id, home_id: 15, away_id: 16, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 15, away_id: 9, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 15, away_id: 10, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 15, away_id: 11, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 15, away_id: 12, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 15, away_id: 13, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 15, away_id: 14, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 16, away_id: 9, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 16, away_id: 10, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 16, away_id: 11, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 16, away_id: 12, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 16, away_id: 13, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 16, away_id: 14, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 16, away_id: 15, home_score: 0, away_score: 0, completed: false)

# Division: The Americas and Oceania Games
Game.create(week_id: Week.all[0].id, home_id: 1, away_id: 2, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 1, away_id: 3, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 1, away_id: 4, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 1, away_id: 5, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 1, away_id: 6, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 1, away_id: 7, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 1, away_id: 8, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 2, away_id: 3, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 2, away_id: 4, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 2, away_id: 5, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 2, away_id: 6, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 2, away_id: 7, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 2, away_id: 8, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 2, away_id: 1, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[0].id, home_id: 3, away_id: 4, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 3, away_id: 5, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 3, away_id: 6, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 3, away_id: 7, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 3, away_id: 8, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 3, away_id: 1, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 3, away_id: 2, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 4, away_id: 5, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 4, away_id: 6, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 4, away_id: 7, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 4, away_id: 8, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 4, away_id: 1, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 4, away_id: 2, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 4, away_id: 3, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[0].id, home_id: 5, away_id: 6, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 5, away_id: 7, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 5, away_id: 8, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 5, away_id: 1, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 5, away_id: 2, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 5, away_id: 3, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 5, away_id: 4, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 6, away_id: 7, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 6, away_id: 8, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 6, away_id: 1, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 6, away_id: 2, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 6, away_id: 3, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 6, away_id: 4, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 6, away_id: 5, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[0].id, home_id: 7, away_id: 8, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 7, away_id: 1, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 7, away_id: 2, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 7, away_id: 3, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 7, away_id: 4, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 7, away_id: 5, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 7, away_id: 6, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 8, away_id: 1, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 8, away_id: 2, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 8, away_id: 3, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 8, away_id: 4, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 8, away_id: 5, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 8, away_id: 6, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 8, away_id: 7, home_score: 0, away_score: 0, completed: false)

# Division: Africa and Western Asia
Game.create(week_id: Week.all[0].id, home_id: 25, away_id: 26, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 25, away_id: 27, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 25, away_id: 28, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 25, away_id: 29, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 25, away_id: 30, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 25, away_id: 31, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 25, away_id: 32, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 26, away_id: 27, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 26, away_id: 28, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 26, away_id: 29, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 26, away_id: 30, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 26, away_id: 31, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 26, away_id: 32, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 26, away_id: 25, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[0].id, home_id: 27, away_id: 28, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 27, away_id: 29, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 27, away_id: 30, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 27, away_id: 31, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 27, away_id: 32, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 27, away_id: 25, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 27, away_id: 26, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 28, away_id: 29, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 28, away_id: 30, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 28, away_id: 31, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 28, away_id: 32, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 28, away_id: 25, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 28, away_id: 26, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 28, away_id: 27, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[0].id, home_id: 29, away_id: 30, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 29, away_id: 31, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 29, away_id: 32, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 29, away_id: 25, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 29, away_id: 26, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 29, away_id: 27, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 29, away_id: 28, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 30, away_id: 31, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 30, away_id: 32, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 30, away_id: 25, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 30, away_id: 26, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 30, away_id: 27, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 30, away_id: 28, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 30, away_id: 29, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[0].id, home_id: 31, away_id: 32, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 31, away_id: 25, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 31, away_id: 26, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 31, away_id: 27, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 31, away_id: 28, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 31, away_id: 29, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 31, away_id: 30, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 32, away_id: 25, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 32, away_id: 26, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 32, away_id: 27, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 32, away_id: 28, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 32, away_id: 29, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 32, away_id: 30, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 32, away_id: 31, home_score: 0, away_score: 0, completed: false)

# Asia Division
Game.create(week_id: Week.all[0].id, home_id: 17, away_id: 18, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 17, away_id: 19, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 17, away_id: 20, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 17, away_id: 21, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 17, away_id: 22, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 17, away_id: 23, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 17, away_id: 24, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 18, away_id: 19, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 18, away_id: 20, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 18, away_id: 21, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 18, away_id: 22, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 18, away_id: 23, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 18, away_id: 24, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 18, away_id: 17, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[0].id, home_id: 19, away_id: 20, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 19, away_id: 21, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 19, away_id: 22, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 19, away_id: 23, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 19, away_id: 24, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 19, away_id: 17, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 19, away_id: 18, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 20, away_id: 21, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 20, away_id: 22, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 20, away_id: 23, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[6].id, home_id: 20, away_id: 24, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 20, away_id: 17, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 20, away_id: 18, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 20, away_id: 19, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[0].id, home_id: 21, away_id: 22, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 21, away_id: 23, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 21, away_id: 24, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 21, away_id: 17, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 21, away_id: 18, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 21, away_id: 19, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 21, away_id: 20, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 22, away_id: 23, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[2].id, home_id: 22, away_id: 24, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 22, away_id: 17, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 22, away_id: 18, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 22, away_id: 19, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[10].id, home_id: 22, away_id: 20, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 22, away_id: 21, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[0].id, home_id: 23, away_id: 24, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 23, away_id: 17, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[4].id, home_id: 23, away_id: 18, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 23, away_id: 19, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[8].id, home_id: 23, away_id: 20, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 23, away_id: 21, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[12].id, home_id: 23, away_id: 22, home_score: 0, away_score: 0, completed: false)

Game.create(week_id: Week.all[1].id, home_id: 24, away_id: 17, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[3].id, home_id: 24, away_id: 18, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[5].id, home_id: 24, away_id: 19, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[7].id, home_id: 24, away_id: 20, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[9].id, home_id: 24, away_id: 21, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[11].id, home_id: 24, away_id: 22, home_score: 0, away_score: 0, completed: false)
Game.create(week_id: Week.all[13].id, home_id: 24, away_id: 23, home_score: 0, away_score: 0, completed: false)

# All Player Games
Game.all.each {|game| game.home.players.each {|player| PlayerGame.create(player_id: player.id, game_id: game.id, quaffle_scored: 0, quaffle_saved: 0, bludger_smashed: 0, snitch_caught: 0, quaffle_shots: 0, quaffle_shots_against: 0) } }
Game.all.each {|game| game.away.players.each {|player| PlayerGame.create(player_id: player.id, game_id: game.id, quaffle_scored: 0, quaffle_saved: 0, bludger_smashed: 0, snitch_caught: 0, quaffle_shots: 0, quaffle_shots_against: 0) } }