# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# america = Team.create(name: "United States of America", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/250px-Flag_of_the_United_States.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
# canada = Team.create(name: "Canada", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/250px-Flag_of_Canada_%28Pantone%29.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
# mexico = Team.create(name: "Mexico", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/250px-Flag_of_Mexico.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
# brazil = Team.create(name: "Brazil", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/250px-Flag_of_Brazil.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
# colombia = Team.create(name: "Republic of Colombia", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/250px-Flag_of_Colombia.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
# argentina = Team.create(name: "Argentine Republic", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/250px-Flag_of_Argentina.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
# venezuela = Team.create(name: "Bolivarian Republic of Venezuela", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Flag_of_Venezuela_%28state%29.svg/250px-Flag_of_Venezuela_%28state%29.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)
# australia = Team.create(name: "Commonwealth of Australia", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/250px-Flag_of_Australia_%28converted%29.svg.png", division: "The Americas and Oceania", wins: 0, losses: 0, points_for: 0, points_against: 0)

# ireland = Team.create(name: "Republic of Ireland", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/250px-Flag_of_Ireland.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
# bulgaria = Team.create(name: "Republic of Bulgaria", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/250px-Flag_of_Bulgaria.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
# russia = Team.create(name: "Russian Federation", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/250px-Flag_of_Russia.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
# germany = Team.create(name: "Federal Republic of Germany", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/250px-Flag_of_Germany.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
# uk = Team.create(name: "United Kingdom", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/250px-Flag_of_the_United_Kingdom.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
# france = Team.create(name: "French Republic", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/250px-Flag_of_France.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
# spain = Team.create(name: "Kingdom of Spain", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/250px-Flag_of_Spain.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)
# ukraine = Team.create(name: "Ukraine", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/250px-Flag_of_Ukraine.svg.png", division: "Europe", wins: 0, losses: 0, points_for: 0, points_against: 0)

# indonesia = Team.create(name: "Republic of Indonesia", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/250px-Flag_of_Indonesia.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# india = Team.create(name: "Republic of India", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/250px-Flag_of_India.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# china = Team.create(name: "People's Republic of China", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/250px-Flag_of_the_People%27s_Republic_of_China.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# bangladesh = Team.create(name: "People's Republic of Bangladesh", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/250px-Flag_of_Bangladesh.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# philippines = Team.create(name: "Republic of the Philippines", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/250px-Flag_of_the_Philippines.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# japan = Team.create(name: "Japan", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Japan%28bordered%29.svg/250px-Flag_of_Japan%28bordered%29.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# korea = Team.create(name: "Republic of Korea", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/250px-Flag_of_South_Korea.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# thailand = Team.create(name: "Kingdom of Thailand", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/250px-Flag_of_Thailand.svg.png", division: "Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)

# turkey = Team.create(name: "Republic of Turkey", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/250px-Flag_of_Turkey.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# pakistan = Team.create(name: "Islamic Republic of Pakistan", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/250px-Flag_of_Pakistan.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# nigeria = Team.create(name: "Federal Republic of Nigeria", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/250px-Flag_of_Nigeria.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# egypt = Team.create(name: "Arab Republic of Egypt", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/250px-Flag_of_Egypt.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# ethiopia = Team.create(name: "Federal Democratic Republic of Ethiopia", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/250px-Flag_of_Ethiopia.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# congo = Team.create(name: "Democratic Republic of the Congo", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/250px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# southafrica = Team.create(name: "Republic of South Africa", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/250px-Flag_of_South_Africa.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)
# tanzania = Team.create(name: "United Republic of Tanzania", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/250px-Flag_of_Tanzania.svg.png", division: "Africa and Western Asia", wins: 0, losses: 0, points_for: 0, points_against: 0)

# Team.all.each do |team| 
#     Player.create(name: Faker::Name.unique.name, position: "Chaser", team: team)
#     Player.create(name: Faker::Name.unique.name, position: "Chaser", team: team)
#     Player.create(name: Faker::Name.unique.name, position: "Chaser", team: team)
#     Player.create(name: Faker::Name.unique.name, position: "Beater", team: team)
#     Player.create(name: Faker::Name.unique.name, position: "Beater", team: team)
#     Player.create(name: Faker::Name.unique.name, position: "Seeker", team: team)
#     Player.create(name: Faker::Name.unique.name, position: "Keeper", team: team)
# end

# Week.create(name: "Week 1", games_completed: false, date: "03 30 2030")
# Week.create(name: "Week 2", games_completed: false, date: "04 06 2030")
# Week.create(name: "Week 3", games_completed: false, date: "04 13 2030")
# Week.create(name: "Week 4", games_completed: false, date: "04 20 2030")
# Week.create(name: "Week 5", games_completed: false, date: "04 27 2030")
# Week.create(name: "Week 6", games_completed: false, date: "05 04 2030")
# Week.create(name: "Week 7", games_completed: false, date: "05 11 2030")
# Week.create(name: "Week 8", games_completed: false, date: "05 18 2030")
# Week.create(name: "Week 9", games_completed: false, date: "05 25 2030")
# Week.create(name: "Week 10", games_completed: false, date: "06 01 2030")
# Week.create(name: "Week 11", games_completed: false, date: "06 08 2030")
# Week.create(name: "Week 12", games_completed: false, date: "06 15 2030")
# Week.create(name: "Week 13", games_completed: false, date: "06 22 2030")
# Week.create(name: "Week 14", games_completed: false, date: "06 29 2030")

# Division: Europe Games
# Game.create(week_id: Week.all[0].id, home_id: 9, away_id: 10, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 9, away_id: 11, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 9, away_id: 12, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 9, away_id: 13, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 9, away_id: 14, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 9, away_id: 15, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 9, away_id: 16, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 10, away_id: 11, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 10, away_id: 12, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 10, away_id: 13, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 10, away_id: 14, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 10, away_id: 15, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 10, away_id: 16, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 10, away_id: 9, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[0].id, home_id: 11, away_id: 12, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 11, away_id: 13, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 11, away_id: 14, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 11, away_id: 15, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 11, away_id: 16, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 11, away_id: 9, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 11, away_id: 10, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 12, away_id: 13, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 12, away_id: 14, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 12, away_id: 15, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 12, away_id: 16, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 12, away_id: 9, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 12, away_id: 10, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 12, away_id: 11, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[0].id, home_id: 13, away_id: 14, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 13, away_id: 15, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 13, away_id: 16, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 13, away_id: 9, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 13, away_id: 10, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 13, away_id: 11, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 13, away_id: 12, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 14, away_id: 15, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 14, away_id: 16, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 14, away_id: 9, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 14, away_id: 10, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 14, away_id: 11, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 14, away_id: 12, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 14, away_id: 13, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[0].id, home_id: 15, away_id: 16, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 15, away_id: 9, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 15, away_id: 10, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 15, away_id: 11, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 15, away_id: 12, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 15, away_id: 13, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 15, away_id: 14, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 16, away_id: 9, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 16, away_id: 10, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 16, away_id: 11, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 16, away_id: 12, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 16, away_id: 13, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 16, away_id: 14, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 16, away_id: 15, home_score: 0, away_score: 0, completed: false)

# Division: The Americas and Oceania Games
# Game.create(week_id: Week.all[0].id, home_id: 1, away_id: 2, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 1, away_id: 3, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 1, away_id: 4, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 1, away_id: 5, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 1, away_id: 6, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 1, away_id: 7, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 1, away_id: 8, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 2, away_id: 3, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 2, away_id: 4, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 2, away_id: 5, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 2, away_id: 6, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 2, away_id: 7, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 2, away_id: 8, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 2, away_id: 1, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[0].id, home_id: 3, away_id: 4, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 3, away_id: 5, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 3, away_id: 6, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 3, away_id: 7, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 3, away_id: 8, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 3, away_id: 1, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 3, away_id: 2, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 4, away_id: 5, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 4, away_id: 6, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 4, away_id: 7, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 4, away_id: 8, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 4, away_id: 1, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 4, away_id: 2, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 4, away_id: 3, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[0].id, home_id: 5, away_id: 6, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 5, away_id: 7, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 5, away_id: 8, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 5, away_id: 1, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 5, away_id: 2, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 5, away_id: 3, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 5, away_id: 4, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 6, away_id: 7, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 6, away_id: 8, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 6, away_id: 1, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 6, away_id: 2, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 6, away_id: 3, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 6, away_id: 4, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 6, away_id: 5, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[0].id, home_id: 7, away_id: 8, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 7, away_id: 1, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 7, away_id: 2, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 7, away_id: 3, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 7, away_id: 4, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 7, away_id: 5, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 7, away_id: 6, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 8, away_id: 1, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 8, away_id: 2, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 8, away_id: 3, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 8, away_id: 4, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 8, away_id: 5, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 8, away_id: 6, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 8, away_id: 7, home_score: 0, away_score: 0, completed: false)

# Division: Africa and Western Asia
# Game.create(week_id: Week.all[0].id, home_id: 25, away_id: 26, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 25, away_id: 27, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 25, away_id: 28, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 25, away_id: 29, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 25, away_id: 30, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 25, away_id: 31, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 25, away_id: 32, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 26, away_id: 27, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 26, away_id: 28, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 26, away_id: 29, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 26, away_id: 30, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 26, away_id: 31, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 26, away_id: 32, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 26, away_id: 25, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[0].id, home_id: 27, away_id: 28, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 27, away_id: 29, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 27, away_id: 30, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 27, away_id: 31, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 27, away_id: 32, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 27, away_id: 25, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 27, away_id: 26, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 28, away_id: 29, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 28, away_id: 30, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 28, away_id: 31, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 28, away_id: 32, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 28, away_id: 25, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 28, away_id: 26, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 28, away_id: 27, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[0].id, home_id: 29, away_id: 30, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 29, away_id: 31, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 29, away_id: 32, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 29, away_id: 25, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 29, away_id: 26, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 29, away_id: 27, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 29, away_id: 28, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 30, away_id: 31, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 30, away_id: 32, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 30, away_id: 25, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 30, away_id: 26, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 30, away_id: 27, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 30, away_id: 28, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 30, away_id: 29, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[0].id, home_id: 31, away_id: 32, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 31, away_id: 25, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 31, away_id: 26, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 31, away_id: 27, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 31, away_id: 28, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 31, away_id: 29, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 31, away_id: 30, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 32, away_id: 25, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 32, away_id: 26, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 32, away_id: 27, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 32, away_id: 28, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 32, away_id: 29, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 32, away_id: 30, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 32, away_id: 31, home_score: 0, away_score: 0, completed: false)

# Asia Division
# Game.create(week_id: Week.all[0].id, home_id: 17, away_id: 18, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 17, away_id: 19, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 17, away_id: 20, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 17, away_id: 21, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 17, away_id: 22, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 17, away_id: 23, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 17, away_id: 24, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 18, away_id: 19, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 18, away_id: 20, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 18, away_id: 21, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 18, away_id: 22, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 18, away_id: 23, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 18, away_id: 24, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 18, away_id: 17, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[0].id, home_id: 19, away_id: 20, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 19, away_id: 21, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 19, away_id: 22, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 19, away_id: 23, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 19, away_id: 24, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 19, away_id: 17, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 19, away_id: 18, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 20, away_id: 21, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 20, away_id: 22, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 20, away_id: 23, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[6].id, home_id: 20, away_id: 24, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 20, away_id: 17, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 20, away_id: 18, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 20, away_id: 19, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[0].id, home_id: 21, away_id: 22, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 21, away_id: 23, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 21, away_id: 24, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 21, away_id: 17, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 21, away_id: 18, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 21, away_id: 19, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 21, away_id: 20, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 22, away_id: 23, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[2].id, home_id: 22, away_id: 24, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 22, away_id: 17, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 22, away_id: 18, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 22, away_id: 19, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[10].id, home_id: 22, away_id: 20, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 22, away_id: 21, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[0].id, home_id: 23, away_id: 24, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 23, away_id: 17, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[4].id, home_id: 23, away_id: 18, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 23, away_id: 19, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[8].id, home_id: 23, away_id: 20, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 23, away_id: 21, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[12].id, home_id: 23, away_id: 22, home_score: 0, away_score: 0, completed: false)

# Game.create(week_id: Week.all[1].id, home_id: 24, away_id: 17, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[3].id, home_id: 24, away_id: 18, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[5].id, home_id: 24, away_id: 19, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[7].id, home_id: 24, away_id: 20, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[9].id, home_id: 24, away_id: 21, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[11].id, home_id: 24, away_id: 22, home_score: 0, away_score: 0, completed: false)
# Game.create(week_id: Week.all[13].id, home_id: 24, away_id: 23, home_score: 0, away_score: 0, completed: false)

# All Player Games
# Game.all.each {|game| game.home.players.each {|player| PlayerGame.create(player_id: player.id, game_id: game.id, quaffle_scored: 0, quaffle_saved: 0, bludger_smashed: 0, snitch_caught: 0) } }
# Game.all.each {|game| game.away.players.each {|player| PlayerGame.create(player_id: player.id, game_id: game.id, quaffle_scored: 0, quaffle_saved: 0, bludger_smashed: 0, snitch_caught: 0) } }